apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: webserver
        image: nginx:1.23.0